"""Add align column to transcription_tasks table

Revision ID: 40350ac54731
Revises: 5f6d57511cad
Create Date: 2025-10-22 12:48:07.376963

"""
from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40350ac54731'
down_revision: Union[str, Sequence[str], None] = '5f6d57511cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_tasks', sa.Column('align_mode', sa.Boolean(), nullable=True))
    op.alter_column('transcription_tasks', 'language',
               existing_type=postgresql.ENUM('RU', 'EN', name='transcription_language'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcription_tasks', 'language',
               existing_type=postgresql.ENUM('RU', 'EN', name='transcription_language'),
               nullable=False)
    op.drop_column('transcription_tasks', 'align_mode')
    # ### end Alembic commands ###
